"""
Code Generator — the metaprogramming heart of AeroDrift.

Rather than string-templating a Python file (fragile, injection-prone,
impossible to validate), this module:

  1. Parses a *generic* remediation template into an AST once
     (``ast.parse``).
  2. Walks the tree with an ``ast.NodeTransformer`` and swaps the
     placeholder ``Constant`` nodes for the exact values pulled from
     the ``DriftFinding`` (security-group id, protocol, ports, CIDR).
  3. Renames the function to something unique & traceable
     (``remediate_drift_sg_0f3a9c1e``), fixes source locations, and
     calls ``ast.unparse`` to emit runnable Python source text.

Because the substitution happens on real AST nodes, the output is
*guaranteed* to be syntactically valid Python — there is no way to
generate a broken f-string or an unbalanced brace the way naive
string formatting could. ``ast.parse`` is run a second time on the
generated source purely as a belt-and-braces sanity check before it
is ever handed to the sandbox executor.
"""

from __future__ import annotations

import ast
import time
from dataclasses import dataclass

from aerodrift.config import AWS_REGION
from aerodrift.graph.topology import DriftFinding

_TEMPLATE = '''
import boto3
from botocore.exceptions import ClientError


def remediate_drift(region_name="__REGION__"):
    """Auto-generated by AeroDrift AST Remediation Engine. Do not hand-edit."""
    security_group_id = "__SG_ID__"
    ec2 = boto3.client("ec2", region_name=region_name)
    ip_permissions = [
        {
            "IpProtocol": "__PROTOCOL__",
            "FromPort": "__FROM_PORT__",
            "ToPort": "__TO_PORT__",
            "IpRanges": [{"CidrIp": "__CIDR__"}],
        }
    ]
    try:
        response = ec2.revoke_security_group_ingress(
            GroupId=security_group_id, IpPermissions=ip_permissions
        )
        print(f"[AeroDrift AST Engine] Executing revoke_security_group_ingress on {security_group_id}")
        return {
            "status": "SUCCESS",
            "resource_id": security_group_id,
            "revoked_permission": ip_permissions[0],
        }
    except ClientError as exc:
        print(f"[AeroDrift AST Engine] Remediation failed for {security_group_id}: {exc}")
        return {"status": "FAILED", "resource_id": security_group_id, "error": str(exc)}
'''

_PLACEHOLDERS = {
    "__REGION__": "region_name",
    "__PROTOCOL__": "protocol",
    "__CIDR__": "cidr",
    "__SG_ID__": "security_group_id",
}
_INT_PLACEHOLDERS = {
    "__FROM_PORT__": "from_port",
    "__TO_PORT__": "to_port",
}


class _PlaceholderSubstitution(ast.NodeTransformer):
    """Swaps template placeholder Constants for real drift-specific values."""

    def __init__(self, values: dict[str, object]) -> None:
        self.values = values

    def visit_Constant(self, node: ast.Constant) -> ast.AST:  # noqa: N802 (ast API)
        if isinstance(node.value, str) and node.value in self.values:
            return ast.copy_location(ast.Constant(value=self.values[node.value]), node)
        return node


@dataclass
class GeneratedRemediation:
    function_name: str
    source_code: str
    ast_node_count: int
    synthesis_ms: float
    finding: DriftFinding


class RemediationCodeGenerator:
    """Synthesizes an exact-fix Python remediation script via the ``ast`` module."""

    def generate_revoke_ingress(
        self, finding: DriftFinding, region_name: str = AWS_REGION
    ) -> GeneratedRemediation:
        start = time.perf_counter()

        tree = ast.parse(_TEMPLATE)

        substitution_values: dict[str, object] = {"__REGION__": region_name}
        substitution_values["__PROTOCOL__"] = finding.protocol
        substitution_values["__CIDR__"] = finding.cidr
        substitution_values["__SG_ID__"] = finding.security_group_id
        substitution_values["__FROM_PORT__"] = finding.from_port
        substitution_values["__TO_PORT__"] = finding.to_port

        tree = _PlaceholderSubstitution(substitution_values).visit(tree)

        # Rename the function so every generated fix is independently
        # addressable/auditable in the execution log.
        function_name = f"remediate_drift_{finding.security_group_id.replace('-', '_')}"
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == "remediate_drift":
                node.name = function_name

        ast.fix_missing_locations(tree)
        source_code = ast.unparse(tree)

        # Sanity check: the emitted source must itself be valid Python.
        ast.parse(source_code)

        node_count = sum(1 for _ in ast.walk(tree))
        synthesis_ms = (time.perf_counter() - start) * 1000

        return GeneratedRemediation(
            function_name=function_name,
            source_code=source_code,
            ast_node_count=node_count,
            synthesis_ms=synthesis_ms,
            finding=finding,
        )
